Bohemia/Controllers/ClienteController.cs
using System.Globalization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProyectoBohemia.Data;
using ProyectoBohemia.Models;

namespace ProyectoBohemia.Controllers;

public class ClienteController : Controller
{
    private readonly ILogger<ClienteController> _logger;
    private ApplicationDbContext _context;

    public ClienteController(
        ILogger<ClienteController> logger,
        ApplicationDbContext context)
    {
        _logger = logger;
        _context = context;
    }

    public IActionResult Index()
    {
        return View();
    }




    public JsonResult ListadoClientes(int clienteID, string nombre)
    {
        var clientes = _context.Clientes.AsQueryable();

        if (!string.IsNullOrEmpty(nombre))
        {
            clientes = clientes.Where(c => c.Nombre.StartsWith(nombre));
        }

        if (clienteID > 0)
        {
            clientes = clientes
                .Where(c => c.ClienteID == clienteID);
        }
        var clienteMostrar = clientes.OrderBy(c => c.Eliminado).ThenBy(C => C.Nombre) .Select(c => new ClienteVista
        {
            ClienteID = c.ClienteID,

            Nombre = c.Nombre,
            Localidad = c.Localidad,
            Telefono = c.Telefono,
            Email = c.Email,
            Dni_cuil = c.Dni_cuil,

          Eliminado = c.Eliminado,

            // ProductoDescripcion = c.Productos.Descripcion.ToString(),
            // ProductoCodigo = c.Productos.Codigo,
            // ProductoPrecioVenta = c.Productos.PrecioVenta,


            // VentaForma_pago = c.Ventas.Forma_pago,
            // VentaTotal = c.Ventas.Total,



        }).ToList();

        return Json(new
        { 
            clientes = clienteMostrar
        });
    }







    public JsonResult GuardarCliente(int clienteID, string nombre, string localidad, string telefono, string email, string dni_cuil)
    {
        string resultado = "";






        if (!String.IsNullOrEmpty(nombre))
        {

            nombre = nombre.ToUpper();

           var existeDni = _context.Clientes.Any(c => c.Dni_cuil == dni_cuil && c.ClienteID != clienteID);

           if (existeDni )
            {
                return Json ("El Dni o cuil ya existen");
            }




            if (clienteID == 0)
            {
                var existeCliente = _context.Clientes.Where(e => e.Nombre == nombre).Count();
                if (existeCliente == 0)
                {
                    var NuevoCliente = new Cliente
                    {
                        Nombre = nombre,
                        Localidad = localidad,
                        Telefono = telefono,
                        Email = email,
                        Dni_cuil = dni_cuil,



                    };
                    _context.Add(NuevoCliente);
                    _context.SaveChanges();
                    resultado = "Cliente guardado";
                }
                else
                {
                    resultado = "Cliente  existente";
                }
            }
            else
            {
                var editarCliente = _context.Clientes.Where(e => e.ClienteID == clienteID).SingleOrDefault();
                if (editarCliente != null)
                {
                    var existeCliente = _context.Clientes.Where(e => e.Nombre == nombre && e.ClienteID != clienteID).Count();
                    if (existeCliente == 0)
                    {
                        editarCliente.Nombre = nombre;
                        editarCliente.Localidad = localidad;
                        editarCliente.Telefono = telefono;
                        editarCliente.Email = email;
                        editarCliente.Dni_cuil = dni_cuil;



                        _context.SaveChanges();
                        resultado = "cliente editado exitosamente";
                    }
                    else
                    {
                        resultado = "cliente existente";
                    }
                }
            }
        }
        else
        {
            resultado = "Debe ingresar un nombre";
        }


        return Json(resultado);
    }





public JsonResult DesactivarCliente(int clienteID, int accion)
{
    var cliente = _context.Clientes.Find(clienteID);

    if (cliente == null)
    {
        return Json(new { success = false });
    }

    cliente.Eliminado = (accion == 1);
    _context.SaveChanges();

    return Json(new { success = true });
}





public JsonResult EliminarCliente(int clienteID)
{
    var eliminarClientes = _context.Clientes.Find(clienteID);

    if (eliminarClientes == null)
    {
        return Json(new { success = false, message = "Producto no encontrado." });
    }

    try
    {
        _context.Clientes.Remove(eliminarClientes);
        _context.SaveChanges();
        return Json(new { success = true });
    }
    catch (Exception ex)
    {
        return Json(new { success = false, message = "Error al eliminar el producto: " + ex.Message });
    }
}


}

Bohemia/Controllers/InformeController.cs
using System.Diagnostics;
using System.Globalization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProyectoBohemia.Data;
using ProyectoBohemia.Models;

namespace ProyectoBohemia.Controllers;

public class InformeController : Controller
{
    private readonly ILogger<InformeController> _logger;
    private readonly ApplicationDbContext _context;

    public InformeController(ILogger<InformeController> logger, ApplicationDbContext context)
    {
        _logger = logger;
        _context = context;
    }

    public IActionResult Index()
    {


        // Crear una lista de SelectListItem que incluya el elemento adicional
        var selectListItems = new List<SelectListItem>
        {
            new SelectListItem { Value = "0", Text = "[SELECCIONE...]" }
        };

        // Obtener todas las opciones del enum
        var enumValues = Enum.GetValues(typeof(Descripcion)).Cast<Descripcion>();

        // Convertir las opciones del enum en SelectListItem
        selectListItems.AddRange(enumValues.Select(e => new SelectListItem
        {
            Value = e.GetHashCode().ToString(),
            Text = e.ToString().ToUpper()
        }));

        // Pasar la lista de opciones al modelo de la vista
        ViewBag.DescripcionBuscar = selectListItems.OrderBy(t => t.Text).ToList();




        return View();
    }




    public JsonResult TraerDetalleVentas(string? DescripcionBuscar, DateTime? fechaDesde, DateTime? fechaHasta)
    {
        List<VentaVistaInforme> detalleVentasMostrar = new List<VentaVistaInforme>();
        


        decimal totalVentasFecha = 0; // Variable para almacenar el total de ventas por fecha
        decimal gananciaTotalFecha = 0;
        var detalleventas = _context.DetalleVentas
            .Include(d => d.Ventas)
            .Include(d => d.Productos)
            .ToList();

        CultureInfo culturaArgentina = new CultureInfo("es-AR");
        Thread.CurrentThread.CurrentCulture = culturaArgentina;
        Thread.CurrentThread.CurrentUICulture = culturaArgentina;

        if (!string.IsNullOrEmpty(DescripcionBuscar) && DescripcionBuscar != "0")
        {
            if (Enum.TryParse(DescripcionBuscar, out Descripcion descripcionEnum))
            {
                detalleventas = detalleventas
                            .Where(d => d.Productos.Descripcion == descripcionEnum)
                            .ToList();
            }

        }

        if (fechaDesde.HasValue && fechaHasta.HasValue)
        {
            DateTime desde = fechaDesde.Value.Date; // Establece la hora en 00:00:00
            DateTime hasta = fechaHasta.Value.Date.AddDays(1).AddTicks(-1); // Fin del día 23:59:59

            detalleventas = detalleventas
                .Where(d => d.Ventas.Fecha_Venta >= desde && d.Ventas.Fecha_Venta <= hasta)
                .ToList();

            totalVentasFecha = detalleventas.Sum(d => d.PrecioUnitario );
gananciaTotalFecha = detalleventas.Sum(d => d.PrecioUnitario - (d.Productos.PrecioCosto * d.Cantidad));
        }
        


        foreach (var detalle in detalleventas)
        {
            var ventaMostrar = detalleVentasMostrar.FirstOrDefault(v => v.VentaID == detalle.VentaID);

            if (ventaMostrar == null)
            {
                ventaMostrar = new VentaVistaInforme
                {
                    VentaID = detalle.VentaID,
                    UsuarioID = detalle.UsuarioID,
                    EmailUsuario = detalle.UsuarioID,
                    Observacion = detalle.Productos.Observacion,

                    Fecha_Venta = detalle.Ventas.Fecha_Venta.Date,
                    Fecha_Ventas = detalle.Ventas.Fecha_Venta.ToString("dd/MM/yyyy"),
                    Forma_pagostring = detalle.Ventas.Forma_pago.ToString(),
                 
                    Total = 0, // Inicializar total en 0 total de la venta dia 
                    GananciaTotal = 0,
                    ListadoDetalle = new List<VistadetalleVenta>()
                };

                detalleVentasMostrar.Add(ventaMostrar);
              
            }
            // Calcular el total de la venta
         var calculoTotal = detalle.PrecioUnitario;

            // Calcular la ganancia (precio de venta - precio de costo)
            var gananciaPorProducto = detalle.PrecioUnitario - detalle.Productos.PrecioCosto * detalle.Cantidad;  // ver con juan


            ventaMostrar.ListadoDetalle.Add(new VistadetalleVenta
            {

                DetalleVentaID = detalle.DetalleVentaID,
                Cantidad = detalle.Cantidad,
                PrecioUnitario = detalle.PrecioUnitario,
                CodigoProducto = detalle.Productos?.Codigo,
                DescripcionProducto = detalle.Productos.Descripcion.ToString(),
                CantidadProducto = detalle.Cantidad,
                PrecioCostoProducto = detalle.Productos?.PrecioCosto ?? 0,
                PrecioVentaProducto = detalle.Productos.PrecioVenta,
                TotalVenta = calculoTotal,
                GananciaProducto = gananciaPorProducto, // Asigna la ganancia de cada producto
                // UsuarioID = detalle.UsuarioID,
                // EmailUsuario = detalle.UsuarioID,



            });



            // Sumar al total de la venta esto es el resultado que da en "total de la venta"
            ventaMostrar.Total += calculoTotal;

            // Sumar la ganancia total
            ventaMostrar.GananciaTotal += gananciaPorProducto;


            //Suma del total feneral del dia 
            // totalVentasFecha += calculoTotal;
            //  gananciaTotalFecha += gananciaPorProducto;
        }

        detalleVentasMostrar = detalleVentasMostrar
              .OrderByDescending(v => v.Fecha_Venta)
              .ToList();


        return Json(new
        {
            detalleVentasMostrar,
            totalVentasFecha,
            gananciaTotalFecha

        });
    }


















    public IActionResult IndexPro()
    {



          return View();
    }

public JsonResult ProductosMinimos()
{
    var productosNoVendidos = _context.Productos
        .Where(p => !_context.DetalleVentas.Any(dv => dv.ProductoID == p.ProductoID))
        .Select(p => new
        {
            ProductoID = p.ProductoID,
            NombreProducto = p.Descripcion,
            DescripcionProducto = p.Descripcion.ToString(),
            CodigoProducto = p.Codigo,
            FechaIngreso = p.FechaIngreso != null ? p.FechaIngreso.ToString("dd-MM-yyyy") : "SIN FECHA",
            CantidadVendida = 0,
            Observaciones = string.IsNullOrEmpty(p.Observacion) ? "NO DEFINIDO" : p.Observacion
        })
        .ToList();

    var productosMenosVendidos = _context.DetalleVentas
        .Include(dv => dv.Productos)
        .GroupBy(dv => dv.ProductoID)
        .Select(g => new
        {
            ProductoID = g.Key,
            NombreProducto = g.First().Productos.Descripcion,
            DescripcionProducto = g.First().Productos.Descripcion.ToString(),
            CodigoProducto = g.First().Productos.Codigo,
            FechaIngreso = g.First().Productos.FechaIngreso != null ? g.First().Productos.FechaIngreso.ToString("dd-MM-yyyy") : "SIN FECHA",
            CantidadVendida = g.Sum(dv => dv.Cantidad),
            Observaciones = string.IsNullOrEmpty(g.First().Productos.Observacion) ? "NO DEFINIDO" : g.First().Productos.Observacion
        })
        .OrderBy(p => p.CantidadVendida)
        .Take(5)
        .ToList();

    var resultado = productosNoVendidos.Concat(productosMenosVendidos).Take(5).ToList();

    return Json(resultado);
}





public JsonResult ProductosMasVendidos()
{
    var productosMasVendidos = _context.DetalleVentas
        .Include(dv => dv.Productos)
        .GroupBy(dv => dv.ProductoID)
        .Select(g => new
        {
            ProductoID = g.Key,
            NombreProducto = g.First().Productos.Descripcion,
          Observaciones = g.First().Productos.Observacion ?? "NO DEFINIDO",
            DescripcionProducto = g.First().Productos.Descripcion.ToString(),
            CodigoProducto = g.First().Productos.Codigo,
 CantidadVendida = g.Sum(dv => dv.Cantidad), // Suma la cantidad total vendida
  FechaIngreso = g.First().Productos.FechaIngreso != null ? g.First().Productos.FechaIngreso.ToString("dd-MM-yyyy") : "SIN FECHA",



        })
        .OrderByDescending(p => p.CantidadVendida) // Ordena de mayor a menor (más vendidos primero)
        .Take(10) // Solo los 5 más vendidos
        .ToList();

    return Json(productosMasVendidos);
}



}

    

Bohemia/Controllers/ProveedorController.cs
using System.Globalization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProyectoBohemia.Data;
using ProyectoBohemia.Models;

namespace ProyectoBohemia.Controllers;

public class ProveedorController : Controller
{
    private readonly ILogger<ProveedorController> _logger;
    private ApplicationDbContext _context;

    public ProveedorController(
        ILogger<ProveedorController> logger,
        ApplicationDbContext context)
    {
        _logger = logger;
        _context = context;
    }

    public IActionResult Index()
    {
        return View();
    }

        public JsonResult ListadoProveedores()
        {
            var proveedores = _context.Proveedores
        
            .ToList();
    
            var proveedorMostrar = proveedores.Select(p => new ProveedorVista
            {
                ProveedorID = p.ProveedorID,
            
                NombreProveedor = p.NombreProveedor,
                Localidad = p.Localidad,
                Telefono = p.Telefono,
                Email = p.Email,
                Cuit = p.Cuit,
                Activo = p.Activo,
    
            }).ToList();
    
            return Json(new
            {
                proveedores = proveedorMostrar
            });
        }


        public JsonResult ObtenerProveedorPorID(int proveedorID)
    {
        var proveedor = _context.Proveedores
            .FirstOrDefault(p => p.ProveedorID == proveedorID);
        if (proveedor == null)
        {
            return Json(new
            {
                success = false,
                message = "Proveedor no encontrado."
            });
        }

        return Json(new
        {
            success = true,
            proveedor = new ProveedorVista
            {
                ProveedorID = proveedor.ProveedorID,
                NombreProveedor = proveedor.NombreProveedor,
                Localidad = proveedor.Localidad,
                Telefono = proveedor.Telefono,
                Email = proveedor.Email,
                Cuit = proveedor.Cuit,
                Activo = proveedor.Activo,
            }
        });

    }

    

    public JsonResult GuardarProveedor(Proveedor proveedor)
{
    // 🔎 Validar EMAIL duplicado
    bool emailExiste = _context.Proveedores.Any(p =>
        p.Email == proveedor.Email &&
        p.ProveedorID != proveedor.ProveedorID
    );

    if (emailExiste)
    {
        return Json(new
        {
            success = false,
            message = "El email ya está registrado en otro proveedor."
        });
    }

    // 🔎 Validar CUIT duplicado
    bool cuitExiste = _context.Proveedores.Any(p =>
        p.Cuit == proveedor.Cuit &&
        p.ProveedorID != proveedor.ProveedorID
    );

    if (cuitExiste)
    {
        return Json(new
        {
            success = false,
            message = "El CUIT ya está registrado en otro proveedor."
        });
    }

    // Alta
    if (proveedor.ProveedorID == 0)
    {
        proveedor.Activo = true;
        _context.Proveedores.Add(proveedor);
    }
    // Edición
    else
    {
        _context.Proveedores.Update(proveedor);
    }

    _context.SaveChanges();

    return Json(new
    {
        success = true,
        message = "Proveedor guardado correctamente."
    });
}



    public JsonResult DesactivarProveedor(int proveedorID, int estado)
    {
        var proveedor = _context.Proveedores.Find(proveedorID);
        if (proveedor == null)
        {
            return Json(new
            {
                success = false,
                message = "Proveedor no encontrado."
            });
        }

        proveedor.Activo = !proveedor.Activo;
        _context.SaveChanges();

            return Json(new
    {
        success = true,
        estadoActual = proveedor.Activo,
        message = proveedor.Activo
            ? "Proveedor activado correctamente."
            : "Proveedor desactivado correctamente."
    });
    }
}

Bohemia/Views/Shared/_Layout.cshtml
@{
    var currentAction = ViewContext.ActionDescriptor.DisplayName;
    var hideSidebar = currentAction.Contains("Login") || currentAction.Contains("Register");
    @using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager


}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProyectoBohemia</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf-autotable/3.6.0/jspdf.plugin.autotable.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Productos.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Home.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/cliente.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/cobro.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProyectoBohemia.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/MDB5/css/mdb.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/wwwroot\fontawesome/css/all.min.css">
    <link rel="stylesheet" href="~/fontawesome/css/all.min.css" asp-append-version="true" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/autonumeric/4.6.0/autoNumeric.min.js"></script>
    <script src="path/to/chartjs/dist/chart.umd.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>


<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/choices.js/public/assets/styles/choices.min.css" />
<script src="https://cdn.jsdelivr.net/npm/choices.js/public/assets/scripts/choices.min.js"></script>

<script>
    const myChart = new Chart(ctx, {...});
</script>


</head>

<body>

    @if (!hideSidebar)
    {
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark border-bottom shadow-sm mb-3 Tamañonav">
            <div class="container-fluid">
                <a class="navbar-brand Textobohemia" asp-area="" asp-controller="Home" asp-action="Index">Bohemia</a>

                <!-- Botón del menú en dispositivos pequeños con icono blanco -->
                <button class="navbar-toggler border-white" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false"
                    aria-label="Toggle navigation">
                    <i class="fas fa-bars text-white"></i>
                </button>
                <!-- Contenedor del menú -->
                <div class="collapse navbar-collapse bg-dark p-3 rounded-bottom" id="navbarNav">
                    <ul class="navbar-nav me-auto">

                        <li class="nav-item">
                            <a class="nav-link text-light Textobohemia" asp-area="" asp-controller="Venta"
                                asp-action="Index">Venta</a>
                        </li>

                                 <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-light Textobohemia" href="#"
                                id="clientesProveedoresDropdown" role="button" data-bs-toggle="dropdown"
                                aria-expanded="false">
                                Clientes y Proveedores
                            </a>

                            <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="clientesProveedoresDropdown">
                                <li>
                                    <a class="dropdown-item Textobohemia" asp-area="" asp-controller="Cliente"
                                        asp-action="Index">
                                        Cliente
                                    </a>
                                </li>

                                <li>
                                    <a class="dropdown-item Textobohemia" asp-area="" asp-controller="Proveedor"
                                        asp-action="Index">
                                        Proveedor
                                    </a>
                                </li>
                            </ul>
                        </li>


                                 <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-light Textobohemia" href="#"
                                id="clientesProveedoresDropdown" role="button" data-bs-toggle="dropdown"
                                aria-expanded="false">
                                Cuenta corriente
                                
                            </a>

                            <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="clientesProveedoresDropdown">
                                <li>
                                    <a class="dropdown-item Textobohemia" asp-area="" asp-controller="Cobro"
                                        asp-action="index">
                                        Cobros
                                    </a>
                                </li>
                                <li>
                                    <a class="dropdown-item Textobohemia" asp-area="" asp-controller="MovimientoCuentaCorriente"
                                        asp-action="Index">
                                        Movimiento Cuenta Corriente
                                    </a>
                                </li>

                                <li>
                                    <a class="dropdown-item Textobohemia" asp-area="" asp-controller="VentaCuotas"
                                        asp-action="Index">
                                        Venta en Cuotas
                                    </a>
                                </li>
                            </ul>
                        </li>

                        @if (User.IsInRole("ADMINISTRADOR"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light Textobohemia" asp-area="" asp-controller="Productos"
                                    asp-action="Index">Producto</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-light Textobohemia" href="#" id="dropdownInforme"
                                    role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Informes
                                </a>
                                <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="dropdownInforme">
                                    <li>
                                        <a class="dropdown-item" asp-controller="Informe" asp-action="Index">Informe</a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" asp-controller="Informe" asp-action="IndexPro">Informe Top</a>
                                    </li>
                                </ul>
                            </li>


                        }


    
                    </ul>
                    <!-- Sección de login -->
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    }

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/autonumeric@4.5.4"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.4.2/mdb.min.js"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>